name: MadeByORiley
favicon: null
layout_spectrum: 0
typography_spectrum: 0.36149
title: Luxury handmade skin care products
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#46473f'
    - '#e25124'
    - '#c0c0b4'
    - '#959056'
  brandStrength: 0.06849267869256437
  lightness: 0.5208014724776149
  saturation: 0.5560138216242194
  rhythmicContrast: 0
purpose: []
